# UCS420 - Cognitive Computing
## NumPy Introduction - 1

## Q1. Create a NumPy 1D array with 5 elements and perform basic operations

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print("Original array:", arr)

add_result = arr + 2
print("After adding 2 to all elements:", add_result)

mul_result = arr * 3
print("After multiplying 3 with all elements:", mul_result)

div_result = arr / 2
print("After dividing every element by 2:", div_result)


Original array: [1 2 3 4 5]
After adding 2 to all elements: [3 4 5 6 7]
After multiplying 3 with all elements: [ 3  6  9 12 15]
After dividing every element by 2: [0.5 1.  1.5 2.  2.5]


## Q2. Questions on Basic NumPy Array

### a) Reverse the NumPy array

In [ ]:
arr = np.array([1, 2, 3, 6, 4, 5])
reversed_arr = arr[::-1]
print("Original array:", arr)
print("Reversed array:", reversed_arr)


Original array: [1 2 3 6 4 5]
Reversed array: [5 4 6 3 2 1]


### b) Find the most frequent value and their indices

In [ ]:
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])

values, counts = np.unique(x, return_counts=True)
most_frequent_x = values[np.argmax(counts)]
indices_x = np.where(x == most_frequent_x)[0]

print("Array x:", x)
print("Most frequent value in x:", most_frequent_x)
print("Indices of most frequent value in x:", indices_x)


Array x: [1 2 3 4 5 1 2 1 1 1]
Most frequent value in x: 1
Indices of most frequent value in x: [0 5 7 8 9]


In [ ]:
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

values, counts = np.unique(y, return_counts=True)
most_frequent_y = values[np.argmax(counts)]
indices_y = np.where(y == most_frequent_y)[0]

print("Array y:", y)
print("Most frequent value in y:", most_frequent_y)
print("Indices of most frequent value in y:", indices_y)


Array y: [1 1 1 2 3 4 2 4 3 3]
Most frequent value in y: 1
Indices of most frequent value in y: [0 1 2]


## Q3. Accessing elements in a 2-D array using row and column indices

In [ ]:
arr = np.array([[10, 20, 30],
                 [40, 50, 60],
                 [70, 80, 90]])
print("2-D array:\n", arr)

a_val = arr[0, 1]
print("Element at 1st row, 2nd column:", a_val)

b_val = arr[2, 0]
print("Element at 3rd row, 1st column:", b_val)


2-D array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
Element at 1st row, 2nd column: 20
Element at 3rd row, 1st column: 70


## Q4. 1-D NumPy array with evenly spaced numbers using linspace()

In [ ]:
Smarth = np.linspace(10, 100, 25)
print("Array:", Smarth)

print("\nDimensions (ndim):", Smarth.ndim)
print("Shape:", Smarth.shape)
print("Total elements (size):", Smarth.size)
print("Data type of each element (dtype):", Smarth.dtype)
print("Total bytes consumed (nbytes):", Smarth.nbytes)


Array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]

Dimensions (ndim): 1
Shape: (25,)
Total elements (size): 25
Data type of each element (dtype): float64
Total bytes consumed (nbytes): 200


### Transpose using reshape()
Since the array is 1-D, `reshape()` can be used to change its shape (for example into a column vector), which acts like a transpose for a 1-D array.

In [ ]:
transposed_reshape = Your_Name.reshape(25, 1)
print("Shape after reshape(25, 1):", transposed_reshape.shape)
print(transposed_reshape)


Shape after reshape(25, 1): (25, 1)
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]


### Can we do the same with the T attribute?
No — for a 1-D array, the `.T` attribute has **no effect**. Transpose only swaps axes, and a 1-D array has just one axis, so `.T` returns the array unchanged (still shape `(25,)`). To truly get a transposed 2-D (row/column) effect, the array must first be reshaped into 2-D (e.g., using `reshape(25, 1)` or `reshape(1, 25)`), after which `.T` will work as expected.

In [ ]:
print("Original shape:", Your_Name.shape)
print("Shape after .T on 1-D array:", Your_Name.T.shape)

reshaped_2d = Your_Name.reshape(1, 25)
print("\nShape of 2-D version:", reshaped_2d.shape)
print("Shape after applying .T on 2-D version:", reshaped_2d.T.shape)


Original shape: (25,)
Shape after .T on 1-D array: (25,)

Shape of 2-D version: (1, 25)
Shape after applying .T on 2-D version: (25, 1)


## Q5. 2-D Array operations - mean, median, max, min, unique, reshape, resize

In [ ]:
ucs420_Your_Name = np.array([[10, 20, 30, 40],
                              [50, 60, 70, 80],
                              [90, 15, 20, 35]])
print("Original array (3x4):\n", ucs420_Your_Name)

mean_val = np.mean(ucs420_Your_Name)
median_val = np.median(ucs420_Your_Name)
max_val = np.max(ucs420_Your_Name)
min_val = np.min(ucs420_Your_Name)
unique_vals = np.unique(ucs420_Your_Name)

print("\nMean:", mean_val)
print("Median:", median_val)
print("Max:", max_val)
print("Min:", min_val)
print("Unique elements:", unique_vals)


Original array (3x4):
 [[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]

Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]


In [ ]:
reshaped_ucs420_Your_Name = ucs420_Your_Name.reshape(4, 3)
print("Reshaped array (4x3):\n", reshaped_ucs420_Your_Name)


Reshaped array (4x3):
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]


In [ ]:
resized_ucs420_Your_Name = np.resize(ucs420_Your_Name, (2, 3))
print("Resized array (2x3):\n", resized_ucs420_Your_Name)


Resized array (2x3):
 [[10 20 30]
 [40 50 60]]
